// <auto-generated />
using System;
using ArmRipper.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArmRipper.Core.Migrations
{
    [DbContext(typeof(ArmDbContext))]
    [Migration("20260723014204_AddGpuIndex")]
    partial class AddGpuIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ArmRipper.Core.Models.ConfigSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDuplicates")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apprise")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmApiKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoEject")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BashScript")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DbFile")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DelRawFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestExt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscDbApiBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DiscDbEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DiscDbMinConfidence")
                        .HasColumnType("REAL");

                    b.Property<bool>("DiscDbRequireConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmbyApiKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmbyPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmbyRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmbyServer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtrasSub")
                        .HasColumnType("TEXT");

                    b.Property<string>("FfmpegCli")
                        .HasColumnType("TEXT");

                    b.Property<string>("FfmpegPostFileArgs")
                        .HasColumnType("TEXT");

                    b.Property<string>("FfmpegPreFileArgs")
                        .HasColumnType("TEXT");

                    b.Property<string>("GetAudioTitle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GetVideoTitle")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GpuIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HbArgsBd")
                        .HasColumnType("TEXT");

                    b.Property<string>("HbArgsDvd")
                        .HasColumnType("TEXT");

                    b.Property<string>("HbPresetBd")
                        .HasColumnType("TEXT");

                    b.Property<string>("HbPresetDvd")
                        .HasColumnType("TEXT");

                    b.Property<string>("IftttKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MainFeature")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualWait")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManualWaitTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxConcurrentMakemkvInfo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxConcurrentTranscodes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataProvider")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MkvArgs")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyRip")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyTranscode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OmdbApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PbKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoUserKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreferWidescreen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Prevent99")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RipMethod")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipTranscode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscodePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("UiBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseFfmpeg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebServerIp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WebServerPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.DiscDbMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaSlug")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaTitle")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaYear")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackMappingsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.ToTable("discdb_mappings", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.DiscMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SectorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VolumeLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("disc_metadata", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.DiscTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AspectRatio")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Chapters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscMetadataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Fps")
                        .HasColumnType("REAL");

                    b.Property<int?>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackNumber")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscMetadataId");

                    b.ToTable("disc_tracks", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.DiscTrackStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChannelCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Forced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscTrackId");

                    b.ToTable("disc_track_streams", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArmVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedStages")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CrcId")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("DevPath")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscDbHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ejected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasNiceTitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTrack99")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbIdAuto")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbIdManual")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobLength")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogFile")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualWaitResume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MountPoint")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NoOfTitles")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginalJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OvidApiResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("OvidFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OvidSubmitted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PidHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrlAuto")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrlManual")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesTmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StageErrors")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StageStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleAuto")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleManual")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoTypeAuto")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoTypeManual")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Warnings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("YearAuto")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManual")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.RipperSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ripper_settings", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.SystemDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveMode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firmware")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobIdCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobIdPrevious")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Maker")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Mdisc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mount")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadBd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadCd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadDvd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Serial")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Stale")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("system_drives", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.SystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArmVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("CpuInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OsInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("RamInfo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("system_info", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AspectRatio")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Chapters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscDbItemSlug")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeTitle")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Fps")
                        .HasColumnType("REAL");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MainFeature")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewFileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrigFileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Process")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ripped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackNumber")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrackSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.UiSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconStyle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RefreshRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ui_settings", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ArmRipper.Core.Models.ConfigSnapshot", b =>
                {
                    b.HasOne("ArmRipper.Core.Models.Job", "Job")
                        .WithOne("Config")
                        .HasForeignKey("ArmRipper.Core.Models.ConfigSnapshot", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ArmRipper.Core.Models.DiscTrack", b =>
                {
                    b.HasOne("ArmRipper.Core.Models.DiscMetadata", "DiscMetadata")
                        .WithMany("Tracks")
                        .HasForeignKey("DiscMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscMetadata");
                });

            modelBuilder.Entity("ArmRipper.Core.Models.DiscTrackStream", b =>
                {
                    b.HasOne("ArmRipper.Core.Models.DiscTrack", "DiscTrack")
                        .WithMany("Streams")
                        .HasForeignKey("DiscTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscTrack");
                });

            modelBuilder.Entity("ArmRipper.Core.Models.Track", b =>
                {
                    b.HasOne("ArmRipper.Core.Models.Job", "Job")
                        .WithMany("Tracks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ArmRipper.Core.Models.DiscMetadata", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("ArmRipper.Core.Models.DiscTrack", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("ArmRipper.Core.Models.Job", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
